const fs = require('fs');
const path = require('path');

const PHOTO_DIR = path.join('assets', 'img', 'photography');
const META_FILE = path.join(PHOTO_DIR, 'albums.json');
const OUTPUT_FILE = path.join('_data', 'photography.yml');
const IMAGE_EXTENSIONS = /\.(jpg|jpeg|png|gif|webp)$/i;

function readMetadata() {
  if (!fs.existsSync(META_FILE)) return {};
  return JSON.parse(fs.readFileSync(META_FILE, 'utf8'));
}

function yamlString(value) {
  return JSON.stringify(String(value || ''));
}

function titleFromFolder(folder) {
  return folder
    .replace(/^\d+-/, '')
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function photoPath(folder, file) {
  return `/assets/img/photography/${folder}/${file}`;
}

function scanAlbums() {
  const metadata = readMetadata();
  const folders = fs.readdirSync(PHOTO_DIR, { withFileTypes: true })
    .filter((item) => item.isDirectory())
    .map((item) => item.name)
    .sort();

  return folders.map((folder) => {
    const meta = metadata[folder] || {};
    const files = fs.readdirSync(path.join(PHOTO_DIR, folder))
      .filter((file) => IMAGE_EXTENSIONS.test(file))
      .sort();

    if (!files.length) return null;

    const coverFile = meta.cover && files.includes(meta.cover) ? meta.cover : files[0];

    return {
      id: folder,
      title: meta.title || titleFromFolder(folder),
      date: meta.date || '',
      location: meta.location || '',
      description: meta.description || '',
      cover: photoPath(folder, coverFile),
      photos: files.map((file) => ({
        src: photoPath(folder, file),
        alt: `${meta.title || titleFromFolder(folder)} - ${file}`,
        caption: (meta.captions && meta.captions[file]) || ''
      }))
    };
  }).filter(Boolean);
}

function toYaml(albums) {
  const lines = [
    '# Auto-generated by scripts/scan-photos.js.',
    '# Edit assets/img/photography/albums.json for album metadata.',
    ''
  ];

  albums.forEach((album) => {
    lines.push(`- id: ${yamlString(album.id)}`);
    lines.push(`  title: ${yamlString(album.title)}`);
    lines.push(`  date: ${yamlString(album.date)}`);
    lines.push(`  location: ${yamlString(album.location)}`);
    lines.push(`  description: ${yamlString(album.description)}`);
    lines.push(`  cover: ${yamlString(album.cover)}`);
    lines.push('  photos:');
    album.photos.forEach((photo) => {
      lines.push(`    - src: ${yamlString(photo.src)}`);
      lines.push(`      alt: ${yamlString(photo.alt)}`);
      lines.push(`      caption: ${yamlString(photo.caption)}`);
    });
  });

  return `${lines.join('\n')}\n`;
}

const albums = scanAlbums();
fs.writeFileSync(OUTPUT_FILE, toYaml(albums));
console.log(`Generated ${OUTPUT_FILE}: ${albums.length} albums, ${albums.reduce((sum, album) => sum + album.photos.length, 0)} photos.`);
